### ISSUE TITLE
Fix attribute parser to support edge-cases

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell-renderer#26]
Current parseAttribute function in `src/component-parser.js` file fails for cases like `onload="this.rel= 'stylesheet'; this.onload=null"`

In current method, we split string on spaces and consider it as separate attribute value combination and then we separate on `=` to find key and value.

**Comment by saurabhdaware** [comment]
@pantharshit00 Do you have any idea on how we can solve this? in #25 how are you adding attributes to node? can we use similar thing to get attributes from node?

**Comment by saurabhdaware** [comment]
So we can use `@babel/parser` to get attributes:
https://astexplorer.net/#/gist/bce6cfbb702ee968a9f8ba96beaf15a1/707f5de6866e24ad1397591b6a0997b5a4e92120

Apart from this we can also use `@babel/parser` for #24

**Comment by pantharshit00** [comment]
@saurabhdaware In #25, I am just appending my attribute before `>` of a html opening tag.

I don't really parse anything because I don't need to parse anything.

Here is the code for that: https://github.com/pantharshit00/abell-renderer/blob/21d4a451f5e3455bf25e6518e10c6fba38afff43/src/post-compilation.js#L4

**Comment by saurabhdaware** [comment]
This will be fixed in https://github.com/abelljs/abell-renderer/tree/next

**Comment by saurabhdaware** [comment]
Hopefully fixed in #27
